name: E2E Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.18'

    - name: Install dependencies
      #run: go mod tidy
      run: echo "Installing dependencies ..."

    - name: Run e2e tests
      #run: go test ./tests/e2e/...
      run: echo "Running unit tests here ..."
